### ISSUE TITLE
More like a help request

### ISSUE THREAD

**Issue by Sniki** [syscl/OS-X-Voodoo-PS2-Controller#6]
@syscl i didn't know how to get in touch with you other than opening a new issue here since what i will ask you is related to this kext.
First of all i just browsed your repositories and i saw what an amazing contribution you did/do to the hackintosh community.
Since my Laptop is a Lenovo ThinkPad L440 and i have replaced the Touchpad with the model of Lenovo T460 with Clickpad (3 Physical Buttons) and ofc the Trackpoint that is in the middle of Keyboard as a cursor.

I do use Tluck Fork of VoodooPS2Controller.kext which works almost perfect except that sometimes the trackpoint doesn't work on cold boots, a restart or two fixes that issue, he did recently implement a enforced passthru but still on some cases the trackpoint won't work, anyway my main attraction here came when i saw that you implemented a gesture for 3D touch which is amazing.

I was wondering if can apply that into Tluck Fork which i did make a fork of it on my Github.
Considering the fact that im a noobie-beginner into this "but i don understand a lot", i was wondering how hard it is to do that and what would be the easiest way to do so.

Thank you for your awesome work.

Sincerely,
Besnik Rrustemi

**Comment by syscl** [comment]
Hi @BesnikRrustemi ,

Sure you can. 3D Touch function is the function I really enjoy!! The way to implement 3D Touch is actually remapping the shortcut combination keys of ```Ctrl+Command(or  Alt)+D```  as three finger gesture.

Here's some the reference [commits](https://github.com/syscl/OS-X-Voodoo-PS2-Controller/commit/de8e5de4593128eff8d91a9efc3c31de467aa873). Note you just need to change @tluck's source like what I am doing in my VoodooPS2(please give all my changes a look to find some hints).

Let me know if you still have questions.

Note: you also need to disable three finger drag for 3D Touch function if I remember correctly. 

syscl

**Comment by Sniki** [comment]
> Note you just need to change @tluck's source like what I am doing in my VoodooPS2(please give all my changes a look to find some hints).<
Note sure what you exactly mean by that:
1. You mean is there a way to merge it with your fork if it doesn't have conflicts.
2. or just make all the changes that you did on the fork of tluck
3. or fork your VoodooPS2Controller and then add the features of tluck ?

Hmm i believe drag is different that swipe right ?, since for now im using:
3 Fingers swipe up for Application Windows
3 Fingers swipe down for Show Desktop
3 Fingers swipe left for Move to next desktop on the right
3 Fingers swipe right for move to next desktop on the left
Basically Mission Control Features.

i did see that you added even some extra other features if im correct - like:
Pinch/spread to zoom in/out
2,3,4 fingers tap & 2,3,4 fingers click
4 fingers swipe gestures (left,right,down,up)

This will take me some time, but i believe i can do it,

Regarding to the commit that you pointed out, i do have some other codes available & some existing, so i believe i should only add what is missing if im correct (which should be the code for 3d touch feature) ?
For example in your kext:
<string>3b d, 37 d, 2 d, 2 u, 37 u, 3b u</string>
while on my fork of tluck:
<string>3b d, 37 d, 7b d, 7b u, 37 u, 3b u</string>

NVM i see that the 3 theres no such features right now so i will gradually add what is missing.

Which i believe its the "2 d" & "2 u" for 3D touch, correct me if im wrong.

Thank you so much for your feedback.

**Comment by Sniki** [comment]
@syscl it seems that it is much harder than expected, i did try but it's something beyond my current skills and will require me a lot of work.

The problem is that the changes are started from Icedman source and the tluck source has different configurations as there are some conflicts with your configuration that i cant seem to merge.
Even though at least only adding 3D touch function would`ve been super satisfying for me.

**Comment by syscl** [comment]
You need to use ioio to determine the keys map as I did [here](https://github.com/icedman/XPS13-9350-hackintosh/issues/1). It will give you some more hints about how I figure out the correct keys. And you may also need @tluck's help, because he knows how to tune VoodooPS2 on Thinkpad!

syscl
